config/routes.rb
Rails.application.routes.draw do
  resources :song_playlists
  resources :playlists
  resources :genres
  resources :artists
  resources :songs
  resources :users
  
  # get '/users', to: 'users#new'
  # post '/users', to: 'users#create'
  root 'home#index'

  resources :sessions
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
  has_many :genres, through: :songs
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :songs
  has_many :artists, through: :songs
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :song_playlists,  dependent: :destroy 
  has_many :songs, through: :song_playlists

  #search button
  def self.search(search)
    if search.present? 
       where("NAME like ?", "%#{search}%")
    else
       self.all
    end
  end
  
  #create a setter method 
  def song_ids=(ids)
    ids.each do |id|
      if !id.blank?
      song = Song.find(id)
  
      self.songs << song
      end 
    end
  end

  # length of playlist
  def playlist_length
    # add length of all songs and display as "- hours, - minutes, - seconds long"
    length = self.songs.sum { |song| song.duration }
    Time.at(length).utc.strftime("%H hours, %M minutes, and %S seconds")
  end

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :genre
  has_many :song_playlists
  has_many :playlists, through: :song_playlists

  def self.search(search)
    # byebug
    if search.present?
      Song.joins(:artist, :genre).where("artists.name like ? or title like ? or genres.name like ?", "%#{search}%", "%#{search}%", "%#{search}%") # how to alter this for apostrophes in the song titles
    else
      self.all
    end
  end

  def length_to_minutes_and_seconds
    Time.at(self.duration).utc.strftime("%M minutes, %S seconds")
  end
end

app/models/song_playlist.rb
class SongPlaylist < ApplicationRecord
  belongs_to :song
  belongs_to :playlist
end

app/models/user.rb
class User < ApplicationRecord
  has_many :playlists,  dependent: :destroy
  has_secure_password
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :password, length: { in: 6..10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :login

    def login
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def authorize
      # unless login
      # flash[:notice] = "You must be logged in to see this page"
      redirect_to root_path if login.nil?
    end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
    before_action :find_params, only: [:show, :edit, :update, :destroy]
    before_action :authorize

    def index
      @playlists = Playlist.search(params[:search])
    end

    def show

    end

    def new
        @playlist = Playlist.new
    end

    def create 
        @playlist = Playlist.new(playlist_params)
    
        if @playlist.save
          redirect_to @playlist
        else
          render :new
        end
    end
    
    def edit
     
    end
    
    def update
        @playlist.update(playlist_params)
        if @playlist.save
          redirect_to @playlist
        else
          render :edit
        end
    end
    
    def destroy
        @playlist.destroy
        flash[:notice] = "Playlist deleted."
        redirect_to playlists_path
    end

    private
    def playlist_params
      params.require(:playlist).permit(:name, :user_id, song_ids: [])
    end

    def find_params
        @playlist = Playlist.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
        @user = User.find_by(username: params[:username])
        # return head(:forbidden) unless @user.authenticate(params[:password])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to @user
        else
            flash.now[:alert] = "Username or password is invalid"
            render action: "new"
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logout Successful"
        redirect_to login_path
    end
end

app/controllers/song_playlists_controller.rb
class SongPlaylistsController < ApplicationController
  before_action :authorize

  def new

  end

  def create
    @song_playlist = SongPlaylist.create(song_id: params[:song_id], playlist_id: params[:playlist_id])

    redirect_to @song_playlist.playlist
  end

  def destroy
    @song_playlist = SongPlaylist.find_by(playlist_id: params[:playlist_id], song_id: params[:song_id])

    @song_playlist.destroy

    flash[:notice] = "Song deleted."
    redirect_to edit_playlist_path(params[:playlist_id])
  end

  private

  def song_playlist_params
    params.require(:song_playlist).permit(:playlist_id, :song_id)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  before_action :authorize
  
  def index
    @songs = Song.search(params[:search])
  end

  def new
    @song = Song.new
  end

  # def destroy
  #   @song.destroy
  #   flash[:notice] = "Song deleted."
  #   redirect_to :back
  # end

  private
  def song_params
    params.require(:song).permit(:title, :duration, :artist_id, :genre_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authorize, only: [:show]

    def index
       @users = Users.all
    end

    def show
        @user = User.find(login.id)
    end

    def new
        @user = User.new
        @errors = flash[:errors]
    end

    def create
        @user = User.create(user_params)
        if @user.valid?
          session[:user_id] = @user.id  
          redirect_to @user
        else
          flash[:errors]= @user.errors.full_messages
          redirect_to new_user_path
        end
    end

    def destroy
        @user = User.find(params[:id])
        session[:user_id] = nil
        @user.destroy
        flash[:notice] = "Profile deleted."
        redirect_to root_path
    end
     
    private
     
    def user_params
        params.require(:user).permit(:name, :username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/song_playlists_helper.rb
module SongPlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/playlists/_form.erb
<%= form_for @playlist  do |f| %>
  <%= f.hidden_field :user_id, value: "#{login.id}" %>
  <h5><%= f.label :name, "Playlist Name:" %></h5>

  <%= f.text_field :name %>
  <button type="button" class="btn btn-secondary" id="createedit">
    <%= ((f.submit "Update Name", class: "button") if @playlist.id ) %>
    <%= ((f.submit "Create Playlist", class: "button") if !@playlist.id ) %>
  </button>
<% end %><br>

  <% @playlist.song_playlists.each do |song_playlist| %>
    <button type="button" class="btn btn-secondary" id="form">
      <%= button_to 'Remove', song_playlist, method: :delete, params: {song_id: song_playlist.song.id, playlist_id: @playlist.id}, class: "buttonto" %>
    </button>
    <%= song_playlist.song.title %>
    <%= song_playlist.song.length_to_minutes_and_seconds %> 
    <br><br>
<% end %>

app/views/playlists/edit.erb
<h1>Edit a Playlist!</h1>
<br>
<%= render "form" %>

app/views/playlists/index.erb
<div class="text-center">
<h1>Playlists!</h1><br>

<%= form_tag playlists_path, method: :get do %>
  <%= text_field_tag :search, params[:search], list: "name" %>
  <datalist id="name">
    <% Playlist.all.each do |playlist| %>
      <option value="<%= playlist.name %>"></option>
    <% end %>
  </datalist>
  <button type="button" class="btn btn-secondary" id="createedit">
    <%= submit_tag "Search", name: nil, class: "button" %>
  </button>
<% end %>
<br>
</div>
<% @playlists.each do |playlist| %>
<ul class="list">
  <h3><%= link_to playlist.name, playlist, class: "a-primary" %></h3> 
</ul>
    <div class="indent">
    <li><%= pluralize(playlist.songs.count, 'song') %></li>
    <li>Created by: <%= playlist.user.name %></li>
    </div>
    <br><br>
<% end%>

app/views/playlists/new.erb
<h1>Create a New Playlist!</h1>
<br>
<%= render "form" %>

app/views/playlists/show.erb
<h1>Your Jamms!</h1>
<br>
<h2><%= @playlist.name %></h2>
<p>This playlist is <%= @playlist.playlist_length%> long.</p>

<button type="button" class="btn btn-secondary">
    <%= mail_to '', "Share this Playlist", subject: "Checkout this Playlist!", body: "Listen here: http://localhost:3000/playlists/#{ @playlist.id }" %>
</button>

<br><br>
<h3>Songs</h3>
<ol>
    <% @playlist.songs.each do |song| %>
    <li>
        <%= song.title %> | <%= song.length_to_minutes_and_seconds %><br>
        <iframe src="https://open.spotify.com/embed/track/<%= song.embed_key %>" width="300" height="80" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe> 
    </li>
    <% end %>
</ol>

<br>
<div class="bottom_buttons">
    <% if @playlist.user_id == session[:user_id] %>
    <button type="button" class="btn btn-secondary"><%= link_to "Edit Playlist", edit_playlist_path, id:"" %></button>  
    <button type="button" class="btn btn-secondary"><%= link_to "Delete Playlist", @playlist, data: {:confirm => 'Are you sure?'}, :method => :delete %></button>
    <% end %>
</div>

app/views/songs/index.erb
<h1>All Songs</h1><br>
<div class="search">
  <%= form_tag songs_path, method: :get do %>
    <%= text_field_tag :search, params[:search], list: "title" %>
    <datalist id="title">
      <% Song.all.each do |song| %>
        <option value="<%= song.title %>"></option>
      <% end %>
      <% Artist.all.each do |artist| %>
        <option value="<%= artist.name %>"></option>
      <% end %>
      <% Genre.all.each do |genre| %>
        <option value="<%= genre.name %>"></option>
      <% end %>
    </datalist>
    <button type="button" class="btn btn-secondary" id="createedit">
      <%= submit_tag "Search", class: 'button' %>
    </button>
  <% end %>
</div>
<br>

<div class="container songs">
  <% @songs.each_slice(3) do |songs| %>
    <div class="row row-cols-3 mt-3">
    <% songs.each do |song| %>
      <div class="col">
      <p><%= song.title %></p>
      <iframe src="https://open.spotify.com/embed/track/<%= song.embed_key %>" width="250" height="80" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
      <%= form_tag '/song_playlists' do %>
      <%= hidden_field_tag "song_id", song.id %>
      <%= select_tag "playlist_id", options_for_select(Playlist.all.select { |p| p.user_id == session[:user_id] }.map { |p| [ p.name, p.id ] }), prompt: "Select a Playlist" %>
      <button type="button" class="btn btn-secondary" id="form">
        <%= submit_tag "Add to Playlist", class: 'button' %>
      </button>
      <% end %>
      </div>
    <% end %>
    </div>
  <% end %>
</div>

app/views/users/new.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="card col-md-3 style="width: 18rem;" style ='background-color: #FA9C6D;'>
      <%= form_for :user, url: '/users' do |f| %>   
        <h3 class="card-title my-4 mx-3 text-center .text-white font-bold">Sign Up</h3>
        <% if @errors %>
          <% @errors.each do |error| %>
          <%= error %><br>
          <% end %>
        <% end %>
          <div class="form-group">
          <div class="col-md-12 mb-3">
            Name: <%= f.text_field :name %>
          </div>
           <div class="col-md-12 mb-3">
            Username: <%= f.text_field :username %>
          </div>
          <div class="col-md-12 mb-3">
            Password: <%= f.password_field :password %>
          </div>
          <div class="col-md-12 mb-3">
          Confirm Password: <%= f.password_field :password_confirmation %>
          </div><br>
          <div class="text-center">
            <%= f.submit "Submit", class: "btn btn-dark" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-3">
    </div>
  </div>
</div>

app/views/users/show.erb
<h1 class="user_greeting">Welcome, <%= login.name %>!</h1>
<br>
<h3>Playlists You've Created</h3><br>
<% @user.playlists.each do |playlist| %>
<ul class="list" >
  <li><%=link_to playlist.name, playlist, class: "a-primary"%></li>
  </ul>
<% end %>
<br>
<button type="button" class="btn btn-secondary"><%= link_to "Create a New Playlist", new_playlist_path %></button>
  <% if login.id == @user.id %>
    <button type="button" class="btn btn-secondary"><%= link_to "Delete this Profile", user_path(@user), method: :delete %> </button>
  <% end %>