config/routes.rb
Rails.application.routes.draw do
  resources :song_playlists
  resources :playlists
  resources :genres
  resources :artists
  resources :songs
  resources :users
  
  # get '/users', to: 'users#new'
  # post '/users', to: 'users#create'
  root 'home#index'

  resources :sessions
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
  has_many :genres, through: :songs
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :songs
  has_many :artists, through: :songs
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :song_playlists,  dependent: :destroy 
  has_many :songs, through: :song_playlists

  #search button
  def self.search(search)
    if search.present? 
       where("NAME like ?", "%#{search}%")
    else
       self.all
    end
  end
  
  #create a setter method 
  def song_ids=(ids)
    ids.each do |id|
      if !id.blank?
      song = Song.find(id)
  
      self.songs << song
      end 
    end
  end

  # length of playlist
  def playlist_length
    # add length of all songs and display as "- hours, - minutes, - seconds long"
    length = self.songs.sum { |song| song.duration }
    Time.at(length).utc.strftime("%H hours, %M minutes, and %S seconds")
  end

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :genre
  has_many :song_playlists
  has_many :playlists, through: :song_playlists

  def self.search(search)
    # byebug
    if search.present?
      Song.joins(:artist, :genre).where("artists.name like ? or title like ? or genres.name like ?", "%#{search}%", "%#{search}%", "%#{search}%") # how to alter this for apostrophes in the song titles
    else
      self.all
    end
  end

  def length_to_minutes_and_seconds
    Time.at(self.duration).utc.strftime("%M minutes, %S seconds")
  end
end

app/models/song_playlist.rb
class SongPlaylist < ApplicationRecord
  belongs_to :song
  belongs_to :playlist
end

app/models/user.rb
class User < ApplicationRecord
  has_many :playlists,  dependent: :destroy
  has_secure_password
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :password, length: { in: 6..10 }
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
        @user = User.find_by(username: params[:username])
        # return head(:forbidden) unless @user.authenticate(params[:password])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to @user
        else
            flash.now[:alert] = "Username or password is invalid"
            render action: "new"
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logout Successful"
        redirect_to login_path
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  before_action :authorize
  
  def index
    @songs = Song.search(params[:search])
  end

  def new
    @song = Song.new
  end

  # def destroy
  #   @song.destroy
  #   flash[:notice] = "Song deleted."
  #   redirect_to :back
  # end

  private
  def song_params
    params.require(:song).permit(:title, :duration, :artist_id, :genre_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authorize, only: [:show]

    def index
       @users = Users.all
    end

    def show
        @user = User.find(login.id)
    end

    def new
        @user = User.new
        @errors = flash[:errors]
    end

    def create
        @user = User.create(user_params)
        if @user.valid?
          session[:user_id] = @user.id  
          redirect_to @user
        else
          flash[:errors]= @user.errors.full_messages
          redirect_to new_user_path
        end
    end

    def destroy
        @user = User.find(params[:id])
        session[:user_id] = nil
        @user.destroy
        flash[:notice] = "Profile deleted."
        redirect_to root_path
    end
     
    private
     
    def user_params
        params.require(:user).permit(:name, :username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/song_playlists_helper.rb
module SongPlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    </head>

    <body>
    <div class="container-fluid">
      <!-- navbar -->
      <nav class="navbar navbar-expand-lg navbar-light navbar-custom">

        <a class="navbar-brand" id="jammin" href="/">JammIn</a>
          <% if session[:user_id] %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
           <li class="nav-item active">
              <a class="nav-link" href="/" id="home-link">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/playlists">Playlists</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href=# id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Profile</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/users/:id">My Account</a>
                <a class="dropdown-item" href="/playlists/new">Create a New Playlist</a>
                <%= link_to 'Delete Account', user_path(session[:user_id]), :method => :delete, class:"dropdown-item"%>

              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/songs">Songs</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/logout"> Log Out <%# link_to "Log Out", logout_path, method: :delete %> </a>
            </li>
          </div>
          <% end%>
        </nav>
      </div>

    <div class="container">
     <%= yield %>

    </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/home.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Jammin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'home', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="home">
    <%= yield %>
  </body>
</html>